### PR TITLE
Add min(max)Properties support

### PR DESCRIPTION
**Pull request by AtHeaven**

### CODE REVIEW

**Comment by nicktrandafil** [comment]
These deserialization parameters will work well only when all data members of the struct are optional. Otherwise one could define non-deserializable structs like in the case  with `max_properties = 1` and
```
struct Foo {
  int x;
  int y;
};
```

I won't accept this, sorry. But I imagine you could achieve your goal if `VarPolicy` had a post-deserialization hook. In this case, you would put the validation code in the lambda of the policy type.

Something like this
```
struct VarPolicy {
  static constexpr auto post_from_variant = [](auto&, auto const&) {};
};

T fromVariantImpl(yenxo::Variant const& x) {
    ...
    Policy::post_from_variant(ret, x);
}
```

I would accept the hook implementation though.

**Comment by AtHeaven** [comment]
Could you please clarify this a bit more?
From the perspective of the Json schema, maxProperties < "required".size() is perfectly fine.
So yes, any object like in your example will not be deserialized, but that's a logical problem of the schema itself.
Your thoughts?

**Comment by nicktrandafil** [comment]
This library doesn't validate input with JSON schema. C++ struct itself is the schema for deserialization. The proposed validation rules don't fit well into the scope of this library even though they could be useful in specific cases like yours. It is hard to understand these parameters outside of that specific use case. `Var` is used to enable deserialization for static structs, so imagine one defines a struct like:

```
struct Foo : Var<Policy> {
    int x;
    int y;
}
```

This struct itself talks that it has 2 data members, why should `Policy` state otherwise? This is not obvious. The rules would introduce into the design confusion.

`post_from_variant` would allow you to solve your problem and have your specific validation rules on your side.

**Comment by AtHeaven** [comment]
Sounds reasonable, thank you so much ;)

**Pull request closed without merging**
